---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
    exclude_fingerprints:
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
